apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-event-analysis-apps.fullname" . }}-ingest
  labels:
    {{- include "llm-event-analysis-apps.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
    echoprometheus-enabled: "true"
  {{- with .Values.ingest.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ingest.service.type }}
  ports:
    - name: http
      port: {{ .Values.ingest.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "llm-event-analysis-apps.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
