apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lea-apps-monitor
  labels:
    release: lea-infra
spec:
  selector:
    matchLabels:
      echoprometheus-enabled: "true"
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      